-- 0002_seed.sql — sample content matching the old demo. Generated by
-- scripts/generate-seed.mjs from src/services/mockData.js — do not hand-edit,
-- rerun the script instead. Applied with the same commands as 0001_init.sql.

-- Organizations
INSERT INTO organizations (id, name, kind) VALUES ('o1', 'Kenya Baseball & Softball Federation', 'National federation');
INSERT INTO organizations (id, name, kind) VALUES ('o2', 'Kenya Schools Baseball Association', 'Schools body');

-- Leagues
INSERT INTO leagues (id, org_id, name, kind, season, blurb) VALUES ('l1', 'o1', 'Kenya Community Series 2026', 'League', '2026', 'Regular-season round robin for community clubs and academies.');
INSERT INTO leagues (id, org_id, name, kind, season, blurb) VALUES ('l2', 'o2', 'Koshien Kenya Qualifier 2026', 'Tournament', '2026', 'Group stage for school and academy teams.');

-- Teams
INSERT INTO teams (id, org_id, name, short, county, region, home_field, founded, type, color, status, about, manager_name, contact_email) VALUES ('t1', 'o1', 'Juja Sluggers', 'JUJ', 'Kiambu', 'Juja, Kiambu', 'Field of Dreams, Juja', 2021, 'Community club', '#0d2240', 'approved', 'A university-town club that trains three evenings a week and runs a beginners session every Saturday.', NULL, NULL);
INSERT INTO team_leagues (team_id, league_id) VALUES ('t1', 'l1');
INSERT INTO team_leagues (team_id, league_id) VALUES ('t1', 'l2');
INSERT INTO teams (id, org_id, name, short, county, region, home_field, founded, type, color, status, about, manager_name, contact_email) VALUES ('t2', 'o1', 'Nairobi Thunder', 'NRB', 'Nairobi', 'Nairobi', 'Nairobi Community Diamond', 2020, 'Community club', '#c8102e', 'approved', 'City club with a strong pitching group and the largest supporters section in the league.', NULL, NULL);
INSERT INTO team_leagues (team_id, league_id) VALUES ('t2', 'l1');
INSERT INTO teams (id, org_id, name, short, county, region, home_field, founded, type, color, status, about, manager_name, contact_email) VALUES ('t3', 'o1', 'Makueni Rising Stars', 'MKN', 'Makueni', 'Wote, Makueni', 'Wote Sports Ground', 2022, 'School academy', '#0a7a42', 'approved', 'Academy side built from local primary and secondary school players.', NULL, NULL);
INSERT INTO team_leagues (team_id, league_id) VALUES ('t3', 'l1');
INSERT INTO team_leagues (team_id, league_id) VALUES ('t3', 'l2');
INSERT INTO teams (id, org_id, name, short, county, region, home_field, founded, type, color, status, about, manager_name, contact_email) VALUES ('t4', 'o1', 'Kakamega Comets', 'KKG', 'Kakamega', 'Kakamega', 'Kakamega Academy Field', 2022, 'School academy', '#6b2d8b', 'approved', 'Western Kenya academy focused on junior development and school tournaments.', NULL, NULL);
INSERT INTO team_leagues (team_id, league_id) VALUES ('t4', 'l1');
INSERT INTO team_leagues (team_id, league_id) VALUES ('t4', 'l2');
INSERT INTO teams (id, org_id, name, short, county, region, home_field, founded, type, color, status, about, manager_name, contact_email) VALUES ('t5', 'o1', 'Kisumu Lake Hawks', 'KSM', 'Kisumu', 'Kisumu', 'Lakeside Diamond', 2021, 'Community club', '#0b6fa4', 'approved', 'Lakeside club known for aggressive base running.', NULL, NULL);
INSERT INTO team_leagues (team_id, league_id) VALUES ('t5', 'l1');
INSERT INTO team_leagues (team_id, league_id) VALUES ('t5', 'l2');
INSERT INTO teams (id, org_id, name, short, county, region, home_field, founded, type, color, status, about, manager_name, contact_email) VALUES ('t6', 'o1', 'Mombasa Tide', 'MSA', 'Mombasa', 'Mombasa', 'Coast Community Diamond', 2023, 'Community club', '#a5470b', 'approved', 'The coast’s newest club, playing its first full season.', NULL, NULL);
INSERT INTO team_leagues (team_id, league_id) VALUES ('t6', 'l1');
INSERT INTO teams (id, org_id, name, short, county, region, home_field, founded, type, color, status, about, manager_name, contact_email) VALUES ('t7', 'o1', 'Nakuru Flamingos', 'NKR', 'Nakuru', 'Nakuru', 'Nakuru Town Diamond', 2021, 'Community club', '#c2255c', 'approved', 'Rift Valley club with a young roster and a growing fan base.', NULL, NULL);
INSERT INTO team_leagues (team_id, league_id) VALUES ('t7', 'l1');
INSERT INTO teams (id, org_id, name, short, county, region, home_field, founded, type, color, status, about, manager_name, contact_email) VALUES ('t8', 'o1', 'Bungoma Bulls', 'BGM', 'Bungoma', 'Bungoma', 'Bungoma Schools Field', 2025, 'School academy', '#374151', 'pending', '', 'Mr. Wekesa', 'bulls@example.org');

-- Players
INSERT INTO players (id, team_id, name, jersey, position, bio) VALUES ('t1-p1', 't1', 'Grace Kiptoo', 16, 'P', '');
INSERT INTO players (id, team_id, name, jersey, position, bio) VALUES ('t1-p2', 't1', 'Kevin Wekesa', 39, 'C', '');
INSERT INTO players (id, team_id, name, jersey, position, bio) VALUES ('t1-p3', 't1', 'Faith Wekesa', 5, '1B', '');
INSERT INTO players (id, team_id, name, jersey, position, bio) VALUES ('t1-p4', 't1', 'Grace Chebet', 13, '2B', '');
INSERT INTO players (id, team_id, name, jersey, position, bio) VALUES ('t1-p5', 't1', 'Victor Musyoka', 24, '3B', '');
INSERT INTO players (id, team_id, name, jersey, position, bio) VALUES ('t1-p6', 't1', 'Purity Njoroge', 22, 'SS', '');
INSERT INTO players (id, team_id, name, jersey, position, bio) VALUES ('t1-p7', 't1', 'Collins Njoroge', 6, 'LF', '');
INSERT INTO players (id, team_id, name, jersey, position, bio) VALUES ('t1-p8', 't1', 'Lilian Chebet', 2, 'CF', '');
INSERT INTO players (id, team_id, name, jersey, position, bio) VALUES ('t1-p9', 't1', 'Cynthia Mutua', 26, 'RF', '');
INSERT INTO players (id, team_id, name, jersey, position, bio) VALUES ('t1-p10', 't1', 'Kevin Musyoka', 42, 'DH', '');
INSERT INTO players (id, team_id, name, jersey, position, bio) VALUES ('t1-p11', 't1', 'Winnie Kilonzo', 44, 'P', '');
INSERT INTO players (id, team_id, name, jersey, position, bio) VALUES ('t2-p1', 't2', 'Grace Kiptoo', 40, 'P', '');
INSERT INTO players (id, team_id, name, jersey, position, bio) VALUES ('t2-p2', 't2', 'Naomi Wanjiku', 4, 'C', '');
INSERT INTO players (id, team_id, name, jersey, position, bio) VALUES ('t2-p3', 't2', 'Winnie Chebet', 32, '1B', '');
INSERT INTO players (id, team_id, name, jersey, position, bio) VALUES ('t2-p4', 't2', 'Allan Chebet', 37, '2B', '');
INSERT INTO players (id, team_id, name, jersey, position, bio) VALUES ('t2-p5', 't2', 'Faith Odhiambo', 2, '3B', '');
INSERT INTO players (id, team_id, name, jersey, position, bio) VALUES ('t2-p6', 't2', 'Festus Wanjiku', 30, 'SS', '');
INSERT INTO players (id, team_id, name, jersey, position, bio) VALUES ('t2-p7', 't2', 'Martin Kamau', 33, 'LF', '');
INSERT INTO players (id, team_id, name, jersey, position, bio) VALUES ('t2-p8', 't2', 'Winnie Atieno', 45, 'CF', '');
INSERT INTO players (id, team_id, name, jersey, position, bio) VALUES ('t2-p9', 't2', 'Dennis Nyaga', 13, 'RF', '');
INSERT INTO players (id, team_id, name, jersey, position, bio) VALUES ('t2-p10', 't2', 'Lilian Achieng', 20, 'DH', '');
INSERT INTO players (id, team_id, name, jersey, position, bio) VALUES ('t2-p11', 't2', 'Beatrice Wekesa', 34, 'P', '');
INSERT INTO players (id, team_id, name, jersey, position, bio) VALUES ('t3-p1', 't3', 'Grace Achieng', 19, 'P', '');
INSERT INTO players (id, team_id, name, jersey, position, bio) VALUES ('t3-p2', 't3', 'Sharon Njoroge', 14, 'C', '');
INSERT INTO players (id, team_id, name, jersey, position, bio) VALUES ('t3-p3', 't3', 'Beatrice Muthoni', 22, '1B', '');
INSERT INTO players (id, team_id, name, jersey, position, bio) VALUES ('t3-p4', 't3', 'Festus Musyoka', 39, '2B', '');
INSERT INTO players (id, team_id, name, jersey, position, bio) VALUES ('t3-p5', 't3', 'Cynthia Barasa', 41, '3B', '');
INSERT INTO players (id, team_id, name, jersey, position, bio) VALUES ('t3-p6', 't3', 'Festus Chebet', 11, 'SS', '');
INSERT INTO players (id, team_id, name, jersey, position, bio) VALUES ('t3-p7', 't3', 'Sharon Musyoka', 6, 'LF', '');
INSERT INTO players (id, team_id, name, jersey, position, bio) VALUES ('t3-p8', 't3', 'Kelvin Atieno', 40, 'CF', '');
INSERT INTO players (id, team_id, name, jersey, position, bio) VALUES ('t3-p9', 't3', 'Allan Kilonzo', 42, 'RF', '');
INSERT INTO players (id, team_id, name, jersey, position, bio) VALUES ('t3-p10', 't3', 'Dennis Barasa', 34, 'DH', '');
INSERT INTO players (id, team_id, name, jersey, position, bio) VALUES ('t3-p11', 't3', 'Mercy Kamau', 18, 'P', '');
INSERT INTO players (id, team_id, name, jersey, position, bio) VALUES ('t4-p1', 't4', 'Ian Achieng', 43, 'P', '');
INSERT INTO players (id, team_id, name, jersey, position, bio) VALUES ('t4-p2', 't4', 'Cynthia Wekesa', 24, 'C', '');
INSERT INTO players (id, team_id, name, jersey, position, bio) VALUES ('t4-p3', 't4', 'Cynthia Simiyu', 41, '1B', '');
INSERT INTO players (id, team_id, name, jersey, position, bio) VALUES ('t4-p4', 't4', 'Faith Kilonzo', 40, '2B', '');
INSERT INTO players (id, team_id, name, jersey, position, bio) VALUES ('t4-p5', 't4', 'Elvis Kilonzo', 3, '3B', '');
INSERT INTO players (id, team_id, name, jersey, position, bio) VALUES ('t4-p6', 't4', 'Brian Omondi', 45, 'SS', '');
INSERT INTO players (id, team_id, name, jersey, position, bio) VALUES ('t4-p7', 't4', 'Kelvin Kariuki', 42, 'LF', '');
INSERT INTO players (id, team_id, name, jersey, position, bio) VALUES ('t4-p8', 't4', 'Cynthia Muthoni', 19, 'CF', '');
INSERT INTO players (id, team_id, name, jersey, position, bio) VALUES ('t4-p9', 't4', 'Dennis Wekesa', 16, 'RF', '');
INSERT INTO players (id, team_id, name, jersey, position, bio) VALUES ('t4-p10', 't4', 'Victor Wanjiku', 14, 'DH', '');
INSERT INTO players (id, team_id, name, jersey, position, bio) VALUES ('t4-p11', 't4', 'Dennis Odhiambo', 35, 'P', '');
INSERT INTO players (id, team_id, name, jersey, position, bio) VALUES ('t5-p1', 't5', 'Ian Achieng', 22, 'P', '');
INSERT INTO players (id, team_id, name, jersey, position, bio) VALUES ('t5-p2', 't5', 'Collins Otieno', 34, 'C', '');
INSERT INTO players (id, team_id, name, jersey, position, bio) VALUES ('t5-p3', 't5', 'Kevin Otieno', 19, '1B', '');
INSERT INTO players (id, team_id, name, jersey, position, bio) VALUES ('t5-p4', 't5', 'Victor Achieng', 26, '2B', '');
INSERT INTO players (id, team_id, name, jersey, position, bio) VALUES ('t5-p5', 't5', 'Mercy Mutua', 7, '3B', '');
INSERT INTO players (id, team_id, name, jersey, position, bio) VALUES ('t5-p6', 't5', 'Winnie Omondi', 25, 'SS', '');
INSERT INTO players (id, team_id, name, jersey, position, bio) VALUES ('t5-p7', 't5', 'Naomi Achieng', 9, 'LF', '');
INSERT INTO players (id, team_id, name, jersey, position, bio) VALUES ('t5-p8', 't5', 'Naomi Mwangi', 43, 'CF', '');
INSERT INTO players (id, team_id, name, jersey, position, bio) VALUES ('t5-p9', 't5', 'Winnie Kimani', 4, 'RF', '');
INSERT INTO players (id, team_id, name, jersey, position, bio) VALUES ('t5-p10', 't5', 'Purity Mwangi', 16, 'DH', '');
INSERT INTO players (id, team_id, name, jersey, position, bio) VALUES ('t5-p11', 't5', 'Lilian Odhiambo', 17, 'P', '');
INSERT INTO players (id, team_id, name, jersey, position, bio) VALUES ('t6-p1', 't6', 'Ian Achieng', 1, 'P', '');
INSERT INTO players (id, team_id, name, jersey, position, bio) VALUES ('t6-p2', 't6', 'Faith Njoroge', 44, 'C', '');
INSERT INTO players (id, team_id, name, jersey, position, bio) VALUES ('t6-p3', 't6', 'Winnie Mutua', 4, '1B', '');
INSERT INTO players (id, team_id, name, jersey, position, bio) VALUES ('t6-p4', 't6', 'Victor Kilonzo', 43, '2B', '');
INSERT INTO players (id, team_id, name, jersey, position, bio) VALUES ('t6-p5', 't6', 'Faith Wekesa', 13, '3B', '');
INSERT INTO players (id, team_id, name, jersey, position, bio) VALUES ('t6-p6', 't6', 'Winnie Kiptoo', 5, 'SS', '');
INSERT INTO players (id, team_id, name, jersey, position, bio) VALUES ('t6-p7', 't6', 'Dennis Kamau', 31, 'LF', '');
INSERT INTO players (id, team_id, name, jersey, position, bio) VALUES ('t6-p8', 't6', 'Purity Kimani', 35, 'CF', '');
INSERT INTO players (id, team_id, name, jersey, position, bio) VALUES ('t6-p9', 't6', 'Samuel Barasa', 11, 'RF', '');
INSERT INTO players (id, team_id, name, jersey, position, bio) VALUES ('t6-p10', 't6', 'Sharon Muthoni', 6, 'DH', '');
INSERT INTO players (id, team_id, name, jersey, position, bio) VALUES ('t6-p11', 't6', 'Ian Simiyu', 18, 'P', '');
INSERT INTO players (id, team_id, name, jersey, position, bio) VALUES ('t7-p1', 't7', 'Ian Achieng', 25, 'P', '');
INSERT INTO players (id, team_id, name, jersey, position, bio) VALUES ('t7-p2', 't7', 'Kelvin Wekesa', 9, 'C', '');
INSERT INTO players (id, team_id, name, jersey, position, bio) VALUES ('t7-p3', 't7', 'Kelvin Wafula', 31, '1B', '');
INSERT INTO players (id, team_id, name, jersey, position, bio) VALUES ('t7-p4', 't7', 'Brian Kilonzo', 22, '2B', '');
INSERT INTO players (id, team_id, name, jersey, position, bio) VALUES ('t7-p5', 't7', 'Winnie Kamau', 27, '3B', '');
INSERT INTO players (id, team_id, name, jersey, position, bio) VALUES ('t7-p6', 't7', 'Joy Barasa', 17, 'SS', '');
INSERT INTO players (id, team_id, name, jersey, position, bio) VALUES ('t7-p7', 't7', 'Martin Kilonzo', 40, 'LF', '');
INSERT INTO players (id, team_id, name, jersey, position, bio) VALUES ('t7-p8', 't7', 'Kevin Kiptoo', 6, 'CF', '');
INSERT INTO players (id, team_id, name, jersey, position, bio) VALUES ('t7-p9', 't7', 'Collins Chebet', 30, 'RF', '');
INSERT INTO players (id, team_id, name, jersey, position, bio) VALUES ('t7-p10', 't7', 'Elvis Kimani', 4, 'DH', '');
INSERT INTO players (id, team_id, name, jersey, position, bio) VALUES ('t7-p11', 't7', 'Elvis Kariuki', 26, 'P', '');

-- Matches
INSERT INTO matches (id, league_id, away_id, home_id, date, venue, status, innings_away, innings_home, hits_away, hits_home, errors_away, errors_home, recap, submitted_by, verified_by, admin_note) VALUES ('m1', 'l1', 't2', 't1', '2026-08-09T10:00:00+03:00', 'Field of Dreams, Juja', 'final', '[1,0,0,2,0,1,0]', '[0,2,0,1,3,0,1]', 8, 12, 2, 1, 'Juja pulled away with a three-run fifth.', 'u-manager', 'u-admin', '');
INSERT INTO matches (id, league_id, away_id, home_id, date, venue, status, innings_away, innings_home, hits_away, hits_home, errors_away, errors_home, recap, submitted_by, verified_by, admin_note) VALUES ('m2', 'l1', 't4', 't3', '2026-08-09T10:00:00+03:00', 'Wote Sports Ground', 'final', '[0,1,0,0,0,0,1]', '[0,0,1,0,0,2,0]', 7, 6, 0, 2, 'Makueni scored twice in the sixth to take a tight game.', 'u-manager', 'u-admin', '');
INSERT INTO matches (id, league_id, away_id, home_id, date, venue, status, innings_away, innings_home, hits_away, hits_home, errors_away, errors_home, recap, submitted_by, verified_by, admin_note) VALUES ('m3', 'l1', 't6', 't5', '2026-08-16T10:00:00+03:00', 'Lakeside Diamond', 'final', '[0,0,2,0,0,1,0]', '[3,0,0,1,0,0,2]', 6, 10, 1, 0, '', 'u-manager', 'u-admin', '');
INSERT INTO matches (id, league_id, away_id, home_id, date, venue, status, innings_away, innings_home, hits_away, hits_home, errors_away, errors_home, recap, submitted_by, verified_by, admin_note) VALUES ('m4', 'l1', 't1', 't7', '2026-08-16T10:00:00+03:00', 'Nakuru Town Diamond', 'final', '[2,0,1,0,0,3,0]', '[0,0,0,1,0,0,0]', 10, 6, 2, 1, 'Juja’s bats woke up in the sixth.', 'u-manager', 'u-admin', '');
INSERT INTO matches (id, league_id, away_id, home_id, date, venue, status, innings_away, innings_home, hits_away, hits_home, errors_away, errors_home, recap, submitted_by, verified_by, admin_note) VALUES ('m5', 'l1', 't3', 't2', '2026-08-23T10:00:00+03:00', 'Nairobi Community Diamond', 'final', '[0,0,0,2,0,0,0]', '[1,1,0,0,4,0,0]', 7, 9, 0, 2, '', 'u-manager', 'u-admin', '');
INSERT INTO matches (id, league_id, away_id, home_id, date, venue, status, innings_away, innings_home, hits_away, hits_home, errors_away, errors_home, recap, submitted_by, verified_by, admin_note) VALUES ('m6', 'l1', 't5', 't4', '2026-08-23T10:00:00+03:00', 'Kakamega Academy Field', 'final', '[1,0,2,0,0,2,0]', '[0,0,0,0,0,0,1]', 8, 5, 1, 0, '', 'u-manager', 'u-admin', '');
INSERT INTO matches (id, league_id, away_id, home_id, date, venue, status, innings_away, innings_home, hits_away, hits_home, errors_away, errors_home, recap, submitted_by, verified_by, admin_note) VALUES ('m7', 'l1', 't7', 't6', '2026-08-30T10:00:00+03:00', 'Coast Community Diamond', 'final', '[0,1,0,0,1,0,0]', '[2,0,0,3,0,0,1]', 6, 11, 2, 1, 'Mombasa’s first home win of the season.', 'u-manager', 'u-admin', '');
INSERT INTO matches (id, league_id, away_id, home_id, date, venue, status, innings_away, innings_home, hits_away, hits_home, errors_away, errors_home, recap, submitted_by, verified_by, admin_note) VALUES ('m8', 'l1', 't3', 't1', '2026-08-30T10:00:00+03:00', 'Field of Dreams, Juja', 'final', '[1,0,0,1,0,0,0]', '[0,4,0,0,2,0,1]', 7, 10, 0, 2, '', 'u-manager', 'u-admin', '');
INSERT INTO matches (id, league_id, away_id, home_id, date, venue, status, innings_away, innings_home, hits_away, hits_home, errors_away, errors_home, recap, submitted_by, verified_by, admin_note) VALUES ('m9', 'l1', 't5', 't2', '2026-09-06T10:00:00+03:00', 'Nairobi Community Diamond', 'final', '[1,0,0,0,2,0,1]', '[0,0,2,0,0,1,0]', 7, 7, 1, 0, 'Kisumu came from behind late in Nairobi.', 'u-manager', 'u-admin', '');
INSERT INTO matches (id, league_id, away_id, home_id, date, venue, status, innings_away, innings_home, hits_away, hits_home, errors_away, errors_home, recap, submitted_by, verified_by, admin_note) VALUES ('m10', 'l1', 't7', 't4', '2026-09-06T10:00:00+03:00', 'Kakamega Academy Field', 'final', '[0,0,1,0,0,1,0]', '[1,0,0,1,0,0,0]', 6, 7, 2, 1, 'Called level at the time limit.', 'u-manager', 'u-admin', '');
INSERT INTO matches (id, league_id, away_id, home_id, date, venue, status, innings_away, innings_home, hits_away, hits_home, errors_away, errors_home, recap, submitted_by, verified_by, admin_note) VALUES ('m11', 'l1', 't1', 't6', '2026-09-13T10:00:00+03:00', 'Coast Community Diamond', 'final', '[1,0,3,0,0,2,1]', '[0,0,0,2,0,0,0]', 12, 5, 0, 2, '', 'u-manager', 'u-admin', '');
INSERT INTO matches (id, league_id, away_id, home_id, date, venue, status, innings_away, innings_home, hits_away, hits_home, errors_away, errors_home, recap, submitted_by, verified_by, admin_note) VALUES ('m12', 'l1', 't5', 't3', '2026-09-13T10:00:00+03:00', 'Wote Sports Ground', 'final', '[0,0,2,0,3,0,0]', '[0,1,0,0,0,0,0]', 8, 5, 1, 0, '', 'u-manager', 'u-admin', '');
INSERT INTO matches (id, league_id, away_id, home_id, date, venue, status, innings_away, innings_home, hits_away, hits_home, errors_away, errors_home, recap, submitted_by, verified_by, admin_note) VALUES ('m13', 'l1', 't2', 't7', '2026-09-13T10:00:00+03:00', 'Nakuru Town Diamond', 'final', '[1,1,0,3,0,0,1]', '[0,0,0,0,2,0,0]', 10, 7, 2, 1, '', 'u-manager', 'u-admin', '');
INSERT INTO matches (id, league_id, away_id, home_id, date, venue, status, innings_away, innings_home, hits_away, hits_home, errors_away, errors_home, recap, submitted_by, verified_by, admin_note) VALUES ('m14', 'l1', 't5', 't1', '2026-09-20T10:00:00+03:00', 'Field of Dreams, Juja', 'pending', '[0,2,0,0,1,0,0]', '[1,0,2,0,0,4,0]', 8, 10, 0, 2, 'Juja’s sixth inning decided it.', 'u-manager', NULL, '');
INSERT INTO matches (id, league_id, away_id, home_id, date, venue, status, innings_away, innings_home, hits_away, hits_home, errors_away, errors_home, recap, submitted_by, verified_by, admin_note) VALUES ('m15', 'l1', 't6', 't4', '2026-09-20T10:00:00+03:00', 'Kakamega Academy Field', 'pending', '[2,0,0,1,0,1,0]', '[0,0,1,0,0,0,2]', 7, 7, 1, 0, '', 'u-manager', NULL, '');
INSERT INTO matches (id, league_id, away_id, home_id, date, venue, status, innings_away, innings_home, hits_away, hits_home, errors_away, errors_home, recap, submitted_by, verified_by, admin_note) VALUES ('m16', 'l1', 't1', 't2', '2026-09-26T10:00:00+03:00', 'Nairobi Community Diamond', 'scheduled', NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, '');
INSERT INTO matches (id, league_id, away_id, home_id, date, venue, status, innings_away, innings_home, hits_away, hits_home, errors_away, errors_home, recap, submitted_by, verified_by, admin_note) VALUES ('m17', 'l1', 't5', 't7', '2026-09-26T14:00:00+03:00', 'Nakuru Town Diamond', 'scheduled', NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, '');
INSERT INTO matches (id, league_id, away_id, home_id, date, venue, status, innings_away, innings_home, hits_away, hits_home, errors_away, errors_home, recap, submitted_by, verified_by, admin_note) VALUES ('m18', 'l1', 't6', 't3', '2026-09-27T10:00:00+03:00', 'Wote Sports Ground', 'scheduled', NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, '');
INSERT INTO matches (id, league_id, away_id, home_id, date, venue, status, innings_away, innings_home, hits_away, hits_home, errors_away, errors_home, recap, submitted_by, verified_by, admin_note) VALUES ('m19', 'l1', 't4', 't2', '2026-10-03T10:00:00+03:00', 'Nairobi Community Diamond', 'scheduled', NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, '');
INSERT INTO matches (id, league_id, away_id, home_id, date, venue, status, innings_away, innings_home, hits_away, hits_home, errors_away, errors_home, recap, submitted_by, verified_by, admin_note) VALUES ('m20', 'l1', 't7', 't3', '2026-10-03T14:00:00+03:00', 'Wote Sports Ground', 'scheduled', NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, '');
INSERT INTO matches (id, league_id, away_id, home_id, date, venue, status, innings_away, innings_home, hits_away, hits_home, errors_away, errors_home, recap, submitted_by, verified_by, admin_note) VALUES ('m21', 'l1', 't4', 't1', '2026-10-04T10:00:00+03:00', 'Field of Dreams, Juja', 'scheduled', NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, '');
INSERT INTO matches (id, league_id, away_id, home_id, date, venue, status, innings_away, innings_home, hits_away, hits_home, errors_away, errors_home, recap, submitted_by, verified_by, admin_note) VALUES ('m22', 'l2', 't4', 't3', '2026-09-05T10:00:00+03:00', 'Wote Sports Ground', 'final', '[0,0,1,0,0,0,0]', '[0,2,0,0,1,0,0]', 5, 8, 2, 1, '', 'u-manager', 'u-admin', '');
INSERT INTO matches (id, league_id, away_id, home_id, date, venue, status, innings_away, innings_home, hits_away, hits_home, errors_away, errors_home, recap, submitted_by, verified_by, admin_note) VALUES ('m23', 'l2', 't5', 't1', '2026-09-05T10:00:00+03:00', 'Field of Dreams, Juja', 'final', '[0,0,0,0,1,0,0]', '[2,0,0,4,0,0,0]', 6, 9, 0, 2, '', 'u-manager', 'u-admin', '');
INSERT INTO matches (id, league_id, away_id, home_id, date, venue, status, innings_away, innings_home, hits_away, hits_home, errors_away, errors_home, recap, submitted_by, verified_by, admin_note) VALUES ('m24', 'l2', 't3', 't1', '2026-09-12T10:00:00+03:00', 'Field of Dreams, Juja', 'final', '[0,0,0,2,0,0,0]', '[1,0,1,0,0,0,2]', 5, 8, 1, 0, '', 'u-manager', 'u-admin', '');
INSERT INTO matches (id, league_id, away_id, home_id, date, venue, status, innings_away, innings_home, hits_away, hits_home, errors_away, errors_home, recap, submitted_by, verified_by, admin_note) VALUES ('m25', 'l2', 't4', 't5', '2026-09-12T10:00:00+03:00', 'Lakeside Diamond', 'final', '[1,0,0,0,0,0,2]', '[0,3,0,0,0,2,0]', 7, 10, 2, 1, '', 'u-manager', 'u-admin', '');
INSERT INTO matches (id, league_id, away_id, home_id, date, venue, status, innings_away, innings_home, hits_away, hits_home, errors_away, errors_home, recap, submitted_by, verified_by, admin_note) VALUES ('m26', 'l2', 't4', 't1', '2026-10-10T10:00:00+03:00', 'Field of Dreams, Juja', 'scheduled', NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, '');
INSERT INTO matches (id, league_id, away_id, home_id, date, venue, status, innings_away, innings_home, hits_away, hits_home, errors_away, errors_home, recap, submitted_by, verified_by, admin_note) VALUES ('m27', 'l2', 't5', 't3', '2026-10-10T14:00:00+03:00', 'Wote Sports Ground', 'scheduled', NULL, NULL, NULL, NULL, NULL, NULL, '', NULL, NULL, '');

-- News
INSERT INTO news (id, tag, date, title, summary) VALUES ('n1', 'Results', '2026-09-14', 'Community Series: weekend results verified', 'Three games from 13 September are now official and counted in the standings.');
INSERT INTO news (id, tag, date, title, summary) VALUES ('n2', 'Tournaments', '2026-09-13', 'Koshien Kenya qualifier: last group games on 10 October', 'Four academies are level enough that both remaining games matter for the table.');
INSERT INTO news (id, tag, date, title, summary) VALUES ('n3', 'Guide', '2026-09-08', 'Share a match recap on WhatsApp in two taps', 'Open any result, choose Recap image, and your phone’s share sheet does the rest.');
