// scripts/generate-seed.mjs — turns src/services/mockData.js into a D1 seed
// migration, so the deployed site starts with the same sample content the
// demo had. Run again any time mockData.js changes: `node scripts/generate-seed.mjs`
// (safe to re-run — it always overwrites migrations/0002_seed.sql).
import { seed } from '../src/services/mockData.js';
import { writeFileSync } from 'node:fs';

const esc = (v) => `'${String(v ?? '').replace(/'/g, "''")}'`;
const val = (v) => (v == null ? 'NULL' : typeof v === 'number' ? v : esc(v));
const lines = ['-- 0002_seed.sql — sample content matching the old demo. Generated by', '-- scripts/generate-seed.mjs from src/services/mockData.js — do not hand-edit,', '-- rerun the script instead. Applied with the same commands as 0001_init.sql.', ''];

lines.push('-- Organizations');
for (const o of seed.organizations) lines.push(`INSERT INTO organizations (id, name, kind) VALUES (${esc(o.id)}, ${esc(o.name)}, ${esc(o.kind)});`);

lines.push('', '-- Leagues');
for (const l of seed.leagues) lines.push(`INSERT INTO leagues (id, org_id, name, kind, season, blurb) VALUES (${esc(l.id)}, ${esc(l.orgId)}, ${esc(l.name)}, ${esc(l.kind)}, ${esc(l.season)}, ${esc(l.blurb)});`);

lines.push('', '-- Teams');
for (const t of seed.teams) {
  lines.push(`INSERT INTO teams (id, org_id, name, short, county, region, home_field, founded, type, color, status, about, manager_name, contact_email) VALUES (${esc(t.id)}, ${esc(t.orgId)}, ${esc(t.name)}, ${esc(t.short)}, ${esc(t.county)}, ${esc(t.region)}, ${esc(t.homeField)}, ${t.founded}, ${esc(t.type)}, ${esc(t.color)}, ${esc(t.status)}, ${esc(t.about)}, ${val(t.managerName)}, ${val(t.contact)});`);
  for (const leagueId of t.leagueIds ?? []) lines.push(`INSERT INTO team_leagues (team_id, league_id) VALUES (${esc(t.id)}, ${esc(leagueId)});`);
}

lines.push('', '-- Players');
for (const p of seed.players) lines.push(`INSERT INTO players (id, team_id, name, jersey, position, bio) VALUES (${esc(p.id)}, ${esc(p.teamId)}, ${esc(p.name)}, ${p.jersey}, ${esc(p.position)}, ${esc(p.bio)});`);

lines.push('', '-- Matches');
for (const m of seed.matches) {
  const inningsAway = m.innings ? esc(JSON.stringify(m.innings.away)) : 'NULL';
  const inningsHome = m.innings ? esc(JSON.stringify(m.innings.home)) : 'NULL';
  lines.push(`INSERT INTO matches (id, league_id, away_id, home_id, date, venue, status, innings_away, innings_home, hits_away, hits_home, errors_away, errors_home, recap, submitted_by, verified_by, admin_note) VALUES (${esc(m.id)}, ${esc(m.leagueId)}, ${esc(m.awayId)}, ${esc(m.homeId)}, ${esc(m.date)}, ${esc(m.venue)}, ${esc(m.status)}, ${inningsAway}, ${inningsHome}, ${val(m.hits?.away)}, ${val(m.hits?.home)}, ${val(m.errors?.away)}, ${val(m.errors?.home)}, ${esc(m.recap)}, ${val(m.submittedBy)}, ${val(m.verifiedBy)}, ${esc(m.adminNote)});`);
}

lines.push('', '-- News');
for (const n of seed.news) lines.push(`INSERT INTO news (id, tag, date, title, summary) VALUES (${esc(n.id)}, ${esc(n.tag)}, ${esc(n.date)}, ${esc(n.title)}, ${esc(n.summary)});`);

writeFileSync(new URL('../migrations/0002_seed.sql', import.meta.url), lines.join('\n') + '\n');
console.log('wrote migrations/0002_seed.sql');
